### ISSUE TITLE
Undefined index 'data'

### ISSUE THREAD

**Issue by DariusIII** [b3rs3rk/steamfront#1]
Class is returning undefined index data from this line:

https://github.com/b3rs3rk/steamfront/blob/master/source/b3rs3rk/steamfront/Main.php#L165

Check for null responses should be added.

Steam returns null for its API if requests exceed 1 per second or 10 bulk requests.

https://www.reddit.com/r/Steam/comments/304dft/steam_store_api_is_there_a_throttling_limit_on/

**Comment by niel** [comment]
To expand on this. The method signature is invalid. `string $filter = ''` should be `string $filter = null` the empty quotes is not valid for a type declaration of type string, so you have to handle the null in the method.
